services:
  analysis:
    image: docker.io/jpauwels/faas-analysis:latest
    pull_policy: missing
    build:
      context: https://github.com/jpauwels/faas-cloud-compatible-templates.git#main:template/flask-python-aws
      additional_contexts:
        function: ./analysis
      args:
        TEST_ENABLED: false
        PYTHON_VERSION: 3.13
    ports:
      - "5001:5000"
    environment:
      CHORD_API: "http://confident-chord-estimator:5000"
      ESSENTIA_API: "http://essentia:5000"
      ESSENTIA_TF_MODELS_API: "http://essentia-tensorflow:5000"
      INSTRUMENTS_API: "http://instrument-identifier:5000"
      L3_API: "http://open-l3:5000"
      QVIM_API: "http://qvim:5000"
      SONIC_ANNOTATOR_API: "http://sonic-annotator:5000"
      OBJECT_STORE_HOSTNAME: "host.docker.internal:32002"
      VECTOR_DB_URI: "http://host.docker.internal:32003"
    volumes:
      - ./analysis/config_multicollections.py:/home/app/function/config.py:ro
      - ./analysis/database_mongo_milvus.py:/home/app/function/database.py:ro
    secrets:
      - database-connection
      - object-store-access-key
      - object-store-secret-key
      - vector-db-token
      - freesound-api-key
      - europeana-api-key
  confident-chord-estimator:
    image: docker.io/jpauwels/faas-confident-chord-estimator:latest
    pull_policy: missing
    build:
      context: https://github.com/jpauwels/faas-cloud-compatible-templates.git#main:template/flask-python-aws
      additional_contexts:
        function: ./confident-chord-estimator
      args:
        ADDITIONAL_PACKAGE: ffmpeg git g++ openblas-dev
        TEST_ENABLED: false
  essentia:
    image: docker.io/jpauwels/faas-essentia:latest
    pull_policy: missing
    build:
      context: ./essentia
  essentia-tensorflow:
    image: docker.io/jpauwels/faas-essentia-tensorflow:latest
    pull_policy: missing
    build:
      context: https://github.com/jpauwels/faas-cloud-compatible-templates.git#main:template/flask-python-aws
      additional_contexts:
        function: ./essentia-tensorflow
      args:
        TEST_ENABLED: false
        PYTHON_VERSION: 3.11
        PYTHON_OS: slim
  instrument-identifier:
    image: docker.io/jpauwels/faas-instrument-identifier:latest
    pull_policy: missing
    build:
      context: ./instrument-identifier
    read_only: false
  open-l3:
    image: docker.io/jpauwels/faas-open-l3:latest
    pull_policy: missing
    build:
      context: https://github.com/jpauwels/faas-cloud-compatible-templates.git#main:template/flask-python-aws
      additional_contexts:
        function: ./open-l3
      args:
        TEST_ENABLED: false
        PYTHON_VERSION: 3.11
        PYTHON_OS: slim
        ADDITIONAL_PACKAGE: libsndfile1
  qvim:
    image: docker.io/jpauwels/faas-qvim:latest
    pull_policy: missing
    build:
      context: https://github.com/jpauwels/faas-cloud-compatible-templates.git#main:template/flask-python-aws
      additional_contexts:
        function: ./qvim
      args:
        TEST_ENABLED: false
        PYTHON_VERSION: 3.13
        PYTHON_OS: slim
        ADDITIONAL_PACKAGE: libsndfile1
  search:
    image: docker.io/jpauwels/faas-search:latest
    pull_policy: missing
    build:
      context: https://github.com/jpauwels/faas-cloud-compatible-templates.git#main:template/flask-python-aws
      additional_contexts:
        function: ./search
      args:
        TEST_ENABLED: false
    ports:
      - "5002:5000"
    environment:
      ANALYSIS_API: "http://analysis:5000"
    volumes:
      - ./search/config_multicollections.py:/home/app/function/config.py:ro
    secrets:
      - database-connection
  sonic-annotator:
    image: docker.io/jpauwels/faas-sonic-annotator:latest
    pull_policy: missing
    build:
      context: ./sonic-annotator
    read_only: false
secrets:
  database-connection:
    file: ./secrets/mongo_credentials.txt
  vector-db-token:
    file: ./secrets/vector_db_token.txt
  object-store-access-key:
    file: ./secrets/minio_access_key.txt
  object-store-secret-key:
    file: ./secrets/minio_secret_key.txt
  freesound-api-key:
    file: ./secrets/freesound_api_key.txt
  europeana-api-key:
    file: ./secrets/europeana_api_key.txt
