provider:
  name: openfaas
  gateway: http://127.0.0.1:8080

functions:
  analysis:
    lang: python3-binary
    handler: ./analysis
    image: jpauwels/faas-audio-analysis:latest
    readonly_root_filesystem: true
    environment_file:
     - env.yml
    environment:
      CHORD_API: 'http://gateway:8080/function/confident-chord-estimator'
      ESSENTIA_API: 'http://gateway:8080/function/essentia'
      ESSENTIA_TF_MODELS_API: 'http://gateway:8080/function/essentia-tensorflow'
      INSTRUMENTS_API: 'http://gateway:8080/function/instrument-identifier'
      SONIC_ANNOTATOR_API: 'http://gateway:8080/function/sonic-annotator'
      read_timeout: 1m
      write_timeout: 60m
      exec_timeout: 60m
      combine_output: false
      write_debug: false
  sonic-annotator:
    lang: dockerfile
    handler: ./sonic-annotator
    image: jpauwels/faas-sonic-annotator:latest
    readonly_root_filesystem: false
    environment:
      read_timeout: 1m
      write_timeout: 5m
      exec_timeout: 5m
      combine_output: false
      write_debug: false
  confident-chord-estimator:
    lang: dockerfile
    handler: ./confident-chord-estimator
    image: jpauwels/faas-confident-chord-estimator:latest
    readonly_root_filesystem: true
    environment:
      read_timeout: 1m
      write_timeout: 5m
      exec_timeout: 5m
      combine_output: false
      write_debug: false
  instrument-identifier:
    lang: dockerfile
    handler: ./instrument-identifier
    image: jpauwels/faas-instrument-identifier
    readonly_root_filesystem: false
    environment:
      read_timeout: 1m
      write_timeout: 5m
      exec_timeout: 5m
      combine_output: false
      write_debug: false
  essentia:
    lang: dockerfile
    handler: ./essentia
    image: jpauwels/faas-essentia:latest
    readonly_root_filesystem: false
    environment:
      read_timeout: 1m
      write_timeout: 5m
      exec_timeout: 5m
      combine_output: false
      write_debug: false
  essentia-tensorflow:
    lang: python3-debian-binary
    handler: ./essentia-tensorflow
    image: jpauwels/faas-essentia-tensorflow:latest
    build_args:
      TEST_ENABLED: false
    readonly_root_filesystem: true
    environment:
      read_timeout: 1m
      write_timeout: 59m
      exec_timeout: 59m
      combine_output: false
      write_debug: false
  search:
    lang: python3-binary
    handler: ./search
    image: jpauwels/faas-audio-search:latest
    readonly_root_filesystem: false
    environment_file:
     - env.yml
    environment:
      ANALYSIS_API: 'http://gateway:8080/function/analysis'
      read_timeout: 1m
      write_timeout: 60m
      exec_timeout: 60m
      combine_output: false
      write_debug: false
