provider:
  name: openfaas
  gateway: http://127.0.0.1:8080

functions:
  analysis:
    lang: python3-binary
    handler: ./analysis
    image: jpauwels/faas-audio-analysis:latest
    readonly_root_filesystem: true
    environment_file:
     - env.yml
    environment:
      read_timeout: 330s
      write_timeout: 330s
      combine_output: false
      write_debug: false
  sonic-annotator:
    lang: dockerfile
    handler: ./sonic-annotator
    image: jpauwels/faas-sonic-annotator:latest
    readonly_root_filesystem: false
    environment:
      read_timeout: 300s
      write_timeout: 300s
      combine_output: false
      write_debug: false
  confident-chord-estimator:
    lang: dockerfile
    handler: ./confident-chord-estimator
    image: jpauwels/faas-confident-chord-estimator:latest
    readonly_root_filesystem: true
    environment:
      read_timeout: 300s
      write_timeout: 300s
      combine_output: false
      write_debug: false
  instrument-identifier:
    lang: dockerfile
    handler: ./instrument-identifier
    image: jpauwels/faas-instrument-identifier
    readonly_root_filesystem: false
    environment:
      read_timeout: 300s
      write_timeout: 300s
      combine_output: false
      write_debug: false
  essentia:
    lang: dockerfile
    handler: ./essentia
    image: jpauwels/faas-essentia:latest
    readonly_root_filesystem: false
    environment:
      read_timeout: 300s
      write_timeout: 300s
      combine_output: false
      write_debug: false
  search:
    lang: python3-binary
    handler: ./search
    image: jpauwels/faas-audio-search:latest
    readonly_root_filesystem: false
    environment_file:
     - env.yml
    environment:
      read_timeout: 300s
      write_timeout: 300s
      combine_output: false
      write_debug: false
