provider:
  name: openfaas
  gateway: http://127.0.0.1:8080

functions:
  analysis:
    lang: python3-http
    handler: ./analysis
    image: docker.io/jpauwels/faas-analysis:latest
    build_args:
      TEST_ENABLED: false
    readonly_root_filesystem: true
    secrets:
      - database-connection
      - freesound-api-key
      - europeana-api-key
      - object-store-readwrite-access
      - object-store-readwrite-secret
      - object-store-readonly-access
      - object-store-readonly-secret
    environment:
      CHORD_API: 'http://gateway:8080/function/confident-chord-estimator'
      ESSENTIA_API: 'http://gateway:8080/function/essentia'
      ESSENTIA_TF_MODELS_API: 'http://gateway:8080/function/essentia-tensorflow'
      INSTRUMENTS_API: 'http://gateway:8080/function/instrument-identifier'
      SONIC_ANNOTATOR_API: 'http://gateway:8080/function/sonic-annotator'
      OBJECT_STORE_HOSTNAME: minio:9000
      read_timeout: 1m
      write_timeout: 60m
      exec_timeout: 60m
      combine_output: false
  sonic-annotator:
    lang: dockerfile
    handler: ./sonic-annotator
    image: docker.io/jpauwels/faas-sonic-annotator:latest
    readonly_root_filesystem: false
    environment:
      read_timeout: 1m
      write_timeout: 5m
      exec_timeout: 5m
      combine_output: false
  confident-chord-estimator:
    lang: python3-http
    handler: ./confident-chord-estimator
    image: docker.io/jpauwels/faas-confident-chord-estimator:latest
    build_args:
      ADDITIONAL_PACKAGE: ffmpeg git g++ openblas-dev
      TEST_ENABLED: false
    readonly_root_filesystem: true
    environment:
      read_timeout: 1m
      write_timeout: 5m
      exec_timeout: 5m
      combine_output: false
  instrument-identifier:
    lang: dockerfile
    handler: ./instrument-identifier
    image: docker.io/jpauwels/faas-instrument-identifier
    readonly_root_filesystem: false
    environment:
      read_timeout: 1m
      write_timeout: 5m
      exec_timeout: 5m
      combine_output: false
  essentia:
    lang: dockerfile
    handler: ./essentia
    image: docker.io/jpauwels/faas-essentia:latest
    readonly_root_filesystem: false
    environment:
      read_timeout: 1m
      write_timeout: 5m
      exec_timeout: 5m
      combine_output: false
  essentia-tensorflow:
    lang: python3-http-debian
    handler: ./essentia-tensorflow
    image: docker.io/jpauwels/faas-essentia-tensorflow:latest
    build_args:
      TEST_ENABLED: false
    readonly_root_filesystem: true
    environment:
      read_timeout: 1m
      write_timeout: 59m
      exec_timeout: 59m
      combine_output: false
  search:
    lang: python3-http
    handler: ./search
    image: docker.io/jpauwels/faas-search:latest
    build_args:
      TEST_ENABLED: false
    readonly_root_filesystem: false
    secrets:
      - database-connection
    environment:
      ANALYSIS_API: 'http://gateway:8080/function/analysis'
      read_timeout: 1m
      write_timeout: 60m
      exec_timeout: 60m
      combine_output: false

configuration:
  templates:
    - name: dockerfile
    - name: python3-http
      source: https://github.com/jpauwels/python-flask-template#binary-payload-response
    - name: python3-http-debian
      source: https://github.com/jpauwels/python-flask-template#binary-payload-response
